### PR TITLE
Add man page

### PR DESCRIPTION
**Pull request by tylerfanelli**

### CODE REVIEW

**Comment by slp** [comment]
Hm... I wonder if committing a pre-formatted man page is the best approach here. I kind of prefer what we did on krunvm, committing them as text files and generating the man pages using asciidoctor: https://github.com/containers/krunvm/commit/8244dd6f302380feb4a7cd19c830a0d177dcf93c

**Comment by tylerfanelli** [comment]
@slp Yea, I like this better. Will re-submit once changes are made.

**Comment by tylerfanelli** [comment]
@slp @crobinso When you get the chance, can you review?

**Comment by crobinso** [comment]
Is the plan to kill `cargo-readme` usage? I'm in favor of that. There should be only one source of truth for long form command descriptions, man page makes sense. Could happen as a follow on commit though.

I see the `COMMAND OVERVIEW` section is just a copy of 
`README.md` content. Content is redundant, and not sure I've seen a section like that in a man page before. I think there should just be a `COMMANDS` section, like in `man systemctl`

If you rename the file to `sevctl.1.adoc` I think we get nicer github formatting

**Comment by tylerfanelli** [comment]
> Is the plan to kill `cargo-readme` usage? I'm in favor of that. There should be only one source of truth for long form command descriptions, man page makes sense. Could happen as a follow on commit though.
> 

Yea, I agree. I added a commit removing the usage of `cargo readme`.

> I see the `COMMAND OVERVIEW` section is just a copy of `README.md` content. Content is redundant, and not sure I've seen a section like that in a man page before. I think there should just be a `COMMANDS` section, like in `man systemctl`
> 

I see what you mean, section removed.

> If you rename the file to `sevctl.1.adoc` I think we get nicer github formatting

Done.

**Comment by tylerfanelli** [comment]
@crobinso When you have the chance, can you re-review?

**Review by crobinso — APPROVED** [review]
LGTM

**Pull request merged**
