### PR TITLE
Add show commands for identifier and VCEK URL.

### PR DESCRIPTION
**Pull request by jplevyak**
Signed-off-by: John Plevyak <jplevyak@gmail.com>

### CODE REVIEW

**Comment by tylerfanelli** [comment]
Thanks for the contribution @jplevyak. Could you squash the commits into one?

**Comment by jplevyak** [comment]
Done

**Comment by tylerfanelli** [comment]
@jplevyak Thanks for the contribution. I'm fine with this overall and will merge. Before I do, could you also edit the command's description in `docs/sevctl.1.adoc` to show the new options for the `show` command ?

**Comment by jplevyak** [comment]
Added documentation PTAL.

**Review by tylerfanelli — APPROVED** [review]
Thanks!

**Pull request merged**
