### PR TITLE
Support HTTP/HTTPS proxies

### PR DESCRIPTION
**Pull request by sarutak**
This PR proposes to support HTTP/HTTPS proxies.
In the current implementation, `sevctl export` fails if the network is behind proxies.
To support proxies, this PR replaces the `http` module with `reqwest` crate, which supports proxies by setting HTTP_PROXY, and HTTPS_PROXY environment variables.

We can use like as follows.
```
export HTTP_PROXY=http://xxx.yyy.zzz:8080
export HTTPS_PROXY=http://xxx.yyy.zzz:8080
sevctl export /path/to/output
```

### CODE REVIEW

**Comment by tylerfanelli** [comment]
@sarutak Thanks for contributing. Can you rebase on the current branch?

**Comment by sarutak** [comment]
@tylerfanelli Thank you for looking at this PR.
I've finished to resolve the conflict.

**Comment by tylerfanelli** [comment]
@sarutak Sure. Can you address the `cargo clippy` warning?

**Comment by sarutak** [comment]
Sorry, I didn't care clippy. Now I've fixed it. Let's wait for the CI.

**Comment by sarutak** [comment]
@tylerfanelli Gentle ping.

**Review by tylerfanelli — APPROVED** [review]

**Comment by tylerfanelli** [comment]
@sarutak LGTM. Thanks!

**Comment by sarutak** [comment]
@tylerfanelli Thank you!

**Pull request merged**
